import { ContextMenuCommandBuilder, ApplicationCommandType, EmbedBuilder } from 'discord.js';

export default {
  data: new ContextMenuCommandBuilder()
    .setName('Describe This User')
    .setType(ApplicationCommandType.User),
    usage: 'Right-click a user and select "Describe This User" to get a creative description of that user.',
  async execute(interaction, conversationHistories, openai, logger, client, userSettings) {
    // Get the target user from the interaction.
    const targetUser = interaction.targetUser;
    if (!targetUser) {
      return interaction.reply({ content: "Couldn't retrieve the selected user.", ephemeral: true });
    }
    
    // Create a prompt for ChatGPT.
    const prompt = `Describe the user with the following details: Username: ${targetUser.username}, Discriminator: ${targetUser.discriminator}. Provide a creative, friendly description that infers personality traits from these details.`;
    
    // Prepare a prompt for ChatGPT without conversation context (one-off request).
    const messages = [
      { role: 'system', content: "You are ChatGPT, a creative assistant. Provide a descriptive, friendly summary of a user's profile based solely on the given details." },
      { role: 'user', content: prompt }
    ];
    
    // Since the main event handler already deferred the reply, proceed with processing.
    try {
      const response = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages,
      });
      const reply = response.choices[0].message.content;
      const embed = new EmbedBuilder()
        .setTitle(`Description for ${targetUser.tag}`)
        .setDescription(reply)
        .setColor(0x0099ff)
        .setFooter({ text: 'Generated by ChatGPT' });
      
      await interaction.editReply({ embeds: [embed] });
      logger.info(`Described user ${targetUser.tag} for ${interaction.user.tag}`);
    } catch (error) {
      logger.error(`Error describing user: ${error}`);
      await interaction.editReply({ content: 'Sorry, an error occurred while describing the user.' });
    }
  },
};
