import { ContextMenuCommandBuilder, ApplicationCommandType, EmbedBuilder } from 'discord.js';

class DescribeUserCommand {
  constructor() {
    this.data = new ContextMenuCommandBuilder()
      .setName('Describe This User')
      .setType(ApplicationCommandType.User);
    this.usage = 'Right-click a user and select "Describe This User" to get a creative description of that user.';
  }

  async execute(interaction, conversationHistories, openai, logger, client, userSettings) {
    const targetUser = interaction.targetUser;
    if (!targetUser) {
      return interaction.reply({ content: "Couldn't retrieve the selected user.", ephemeral: true });
    }

    const prompt = `Describe the user with the following details: Username: ${targetUser.username}, Discriminator: ${targetUser.discriminator}. Provide a creative, friendly description that infers personality traits from these details.`;

    const messages = [
      { role: 'system', content: "You are ChatGPT, a creative assistant. Provide a descriptive, friendly summary of a user's profile based solely on the given details." },
      { role: 'user', content: prompt }
    ];

    try {
      const response = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages,
      });
      const reply = response.choices[0].message.content;
      const embed = new EmbedBuilder()
        .setTitle(`Description for ${targetUser.tag}`)
        .setDescription(reply)
        .setColor(0x0099ff)
        .setFooter({ text: 'Generated by ChatGPT' });

      await interaction.editReply({ embeds: [embed] });
      logger.info(`Described user ${targetUser.tag} for ${interaction.user.tag}`);
    } catch (error) {
      logger.error(`Error describing user: ${error}`);
      await interaction.editReply({ content: 'Sorry, an error occurred while describing the user.' });
    }
  }
}

export default new DescribeUserCommand();
